'''
Created on 15/10/2012

@author: mac
'''

XML = """
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<fichero_consumos_variables>
<fecha_envio>2012-07-27T15:34:54.198Z</fecha_envio>
<consumos_variables total_registros="4">
    <consumo_variable>
        <id>1</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561727</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>348.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones>
    </consumo_variable>
    <consumo_variable>
        <id>2</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561718</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>1.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones>
    </consumo_variable>
    <consumo_variable
        <id>3</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561729</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>339.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones>
    </consumo_variable>
    <consumo_variable>
        <id>4</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561729</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>187.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones
    </consumo_variable>
    <consumo_variable>
        <id>4</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561729</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>187.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones
    </consumo_variable>
    <consumo_variable>
        <id>4</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561729</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>187.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones
    </consumo_variable>
    <consumo_variable>
        <id>4</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561729</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>187.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones
    </consumo_variable>
    <consumo_variable>
        <id>4</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561729</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>187.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones
    </consumo_variable>
    <consumo_variable>
        <id>4</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561729</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>187.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones
    </consumo_variable>
    <consumo_variable>
        <id>4</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561729</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>187.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones
    </consumo_variable>
    <consumo_variable>
        <id>4</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561729</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>187.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones
    </consumo_variable>
    <consumo_variable>
        <id>4</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561729</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>187.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones
    </consumo_variable>
    <consumo_variable>
        <id>4</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561729</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>187.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones
    </consumo_variable>
    <consumo_variable>
        <id>4</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561729</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>187.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones
    </consumo_variable>
    <consumo_variable>
        <id>4</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561729</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>187.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones
    </consumo_variable>
    <consumo_variable>
        <id>4</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561729</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>187.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones
    </consumo_variable>
    <consumo_variable>
        <id>4</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561729</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>187.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones
    </consumo_variable>
    <consumo_variable>
        <id>4</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561729</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>187.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones
    </consumo_variable>
    <consumo_variable>
        <id>4</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561729</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>187.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones
    </consumo_variable>
    <consumo_variable>
        <id>4</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561729</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>187.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones
    </consumo_variable>
        <consumo_variable>
        <id>4</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561729</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>187.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones
    </consumo_variable>
    <consumo_variable>
        <id>4</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561729</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>187.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones
    </consumo_variable>
        <consumo_variable>
        <id>4</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561729</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>187.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones
    </consumo_variable>
    <consumo_variable>
        <id>4</id>
        <contrato>mac</contrato>
        <servicio_comercial>0</servicio_comercial>
        <concepto_facturable>1905561729</concepto_facturable>
        <fecha_consumo>2012-07Z</fecha_consumo>
        <unidades>187.0</unidades>
        <posicion>1</posicion>
        <total_posiciones>1</total_posiciones
    </consumo_variable>
</consumos_variables>
</fichero_consumos_variables>
"""
